name: Send Post to GitHub Pages

on:
  workflow_call:

jobs:
  create-post-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch (where your Jekyll source files are located)
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: hmeriann/bc
          ref: gh-pages  # Change to the branch where your Jekyll source is stored
            
      # Fetch content for the post from an external source (e.g., API or another workflow)
      - name: Fetch content for the post
        run: |
          content=$(cat issue_body*/issue_body*/*)
          echo $content > post_content.txt

      - name: Create Jekyll post
        run: |
          # Set the date and title for the new post
          post_date=$(date +'%Y-%m-%d')
          post_title="Nightly Build Status Report"

          # Create the post file in the _posts directory (Jekyll format)
          echo "---" > "_posts/$post_date-$post_title.md"
          echo "layout: post" >> "_posts/$post_date-$post_title.md"
          echo "title: $post_title" >> "_posts/$post_date-$post_title.md"
          echo "date: $post_date" >> "_posts/$post_date-$post_title.md"
          echo "$content" >> "_posts/$post_date-$post_title.md"

      # Commit the new post and push it to the gh-pages branch
      - name: Commit and push new post
        run: |
          # Setup Git configuration
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Add and commit the new post
          git add _posts/$post_date-$post_title.md
          git commit -m "Add new post: $post_title"

          # Push to gh-pages branch
          git push origin main  # Change this to the branch you're using for GitHub Pages if needed

      # Deploy to GitHub Pages (GH Pages deploy)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch used for GitHub Pages (can be `main` if set up that way)
          folder: .  # The folder that contains your Jekyll website (usually the root of the repo)

