name: Test - Benchmark timings (RN)
on:
  workflow_dispatch:
env:
  gh_issue_repo: hmeriann/test_
  GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: Build DuckDB versions and link the benchmarks
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_BENCHMARK: 1
      BUILD_TPCH: 1
      BUILD_TPCDS: 1
      BUILD_HTTPFS: 1
      BUILD_JEMALLOC: 1
      CORE_EXTENSIONS: "inet"

    steps:
      - uses: actions/checkout@v4
        with:
          repository: hmeriann/duckdb
          ref: real-nest-test
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests

      - name: Build
        shell: bash
        run: |
          wget https://duckdb-blobs.s3.amazonaws.com/realnest_benchmark_data.duckdb --output-document realnest_benchmark_data.duckdb
          make 
          cd ..
  
      # - name: Set up benchmarks
      #   shell: bash
      #   run: |
      #     cp -r benchmark duckdb/
        
      - run: |
          python scripts/regression_test_runner.py --old=duckdb/build/release/benchmark/benchmark_runner --new=build/release/benchmark/benchmark_runner --benchmarks=.github/regression/realnest_test.csv  --verbose --threads=2 >> real_nest.txt
 
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          path: real_nest.txt
          name: real_nest.txt
