name: Test - Benchmark timings (RN)
on:
  workflow_dispatch:
env:
  gh_issue_repo: hmeriann/test_
  GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: Build DuckDB versions and link the benchmarks
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_BENCHMARK: 1
      BUILD_HTTPFS: 1
      BUILD_JSON: 1

    steps:
      - uses: actions/checkout@v4
        with:
          repository: hmeriann/duckdb
          ref: eb5cd8a9d9da8153c8638b24b9663a2fdedbe7ba
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests

      - run: ls -lah
      - run: git status
      - name: Build
        shell: bash
        run: |
          make 
          cd ..
          
      # - run: ls -lah ./build/release/benchmark
      - run: ls -lah
      # - run: ls -lah benchmark/realnest/benchmarks
        
      - run: |
          python scripts/regression_test_runner.py --old=build/release/benchmark/benchmark_runner --new=build/release/benchmark/benchmark_runner --benchmarks=.github/regression/realnest_test.csv  --verbose --threads=2
 
      # - name: Upload result
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: real_nest.txt
      #     name: real_nest.txt
