name: Calling Nightly Builds Check
on:
  schedule:
    - cron: 0 9 * * * # runs at 10am CET DAILY
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
  gh_repo: duckdb/duckdb
jobs:
  linux:
    name: Check LinuxRelease
    strategy:
      matrix:
        extension: [ arrow, autocomplete, aws, azure, delta, excel, fts, httpfs, iceberg, icu, inet, jemalloc, json, motherduck, mysql_scanner, parquet, postgres_scanner, shell, spatial, sqlite_scanner, substrait, tpcds, tpch, vss ]
        platform: [ linux, linux-aarch64 ]
        version: [ linux-amd64, linux-aarch64 ]
        exclude:
          - platform: linux
            version: linux-aarch64
          - platform: linux-aarch64
            version: linux-amd64
    uses: ./.github/workflows/nrc.yml
    with:
      nightly-build: LinuxRelease
      runs-on: ubuntu-latest
      platform: ${{ matrix.platform }}
      version: ${{ matrix.version }}
      extension: ${{ matrix.extension }}
    
  osx:
    name: Check OSX
    uses: ./.github/workflows/nrc.yml
    with:
      nightly-build: OSX
      platform: osx
      runs-on: macos-latest
  
  create-issue:
    runs-on: ubuntu-latest
    needs:
      - linux
      - osx
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: issues*
          path: issues
      - name: Report an issue
        run: |
          cat issues/issues*.txt/* > report.txt
          gh issue create --repo hmeriann/test_ --title "Nightly Builds Failures" --body-file report.txt

