name: Test - Disable Timeout
on:
  workflow_dispatch:

jobs:
  disable-timeout:
    name: flag
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ['large/tpch.csv', 'tpcds.csv', 'large/ingestion.csv', 'micro_extended.csv', 'large/tpcds.csv']
        
    steps:        
      - name: Use Flag
        continue-on-error: true
        shell: bash
        run: |
          export disable_timeout=""
          if [[ ${{ matrix.test }} == large/tpcds.csv ]]; then
            disable_timeout="--disable-timeout"
          fi
          echo ${{ matrix.test }} ⚠️ $disable_timeout ⏹️
