name: Test - link creation
on:
  push:
env:
  gh_repo: hmeriann/test_
  GH_TOKEN: ${{ github.token }}
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh run list --repo ${{ env.gh_repo }}
          echo ${{ env.gh_repo }}
