name: Test - link creation
on:
  push:
env:
  gh_repo: hmeriann/test_
  GH_TOKEN: ${{ github.token }}
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh run list --repo ${{ env.gh_repo }}
          gh issue create --repo ${{ env.gh_repo }} --title "Test Issue" --body "See ${{ github.server_url }}/${{ env.gh_repo }}/actions/runs/11616401424"
