name: HV_CIFuzz
on:
  workflow_dispatch:
  schedule:
    - cron: "*/107 * * * *"

jobs:
  build-duckdb:
    name: Build DuckDB
    uses: duckdblabs/duckdb-fuzzer-ci/.github/workflows/build_fuzzer.yml@main
    with:
      git_url: hmeriann/duckdb_sqlsmith
      git_tag: random-values-from-file
      timeout-minutes: 120

  fuzzer:
    name: Fuzzer
    needs:
    - build-duckdb
    strategy:
      fail-fast: false
      matrix:
        fuzzer: [duckfuzz, sqlsmith, duckfuzz_functions]
        data: [alltypes, tpch, emptyalltypes]
        enable_verification: [true, false]
        exclude:
          - enable_verification: true
            fuzzer: sqlsmith
          - enable_verification: true
            fuzzer: duckfuzz_functions
    uses: ./.github/workflows/test_H_vals.yml
    with:
      fuzzer: ${{ matrix.fuzzer }}
      data: ${{ matrix.data }}
      timeout-minutes: 120
      max_queries: 1000
      no-git-checks: false
      enable_verification: ${{ matrix.enable_verification }}
    secrets:
      FUZZEROFDUCKSKEY: ${{ secrets.FUZZEROFDUCKSKEY }}
      DUCKDB_HASH: ${{ needs.build-duckdb.outputs.duckdb-hash }}
