name: HV_CIFuzz
on:
  workflow_dispatch:

jobs:
  build-duckdb:
    name: Build DuckDB
    uses: duckdblabs/duckdb-fuzzer-ci/.github/workflows/build_fuzzer.yml@main
    with:
      git_url: hmeriann/duckdb_sqlsmith
      git_tag: random-values-from-file
      timeout-minutes: 120

  fuzzer:
    name: Fuzzer
    needs:
    - build-duckdb
    strategy:
      fail-fast: false
      matrix:
        fuzzer: [duckfuzz, sqlsmith, duckfuzz_functions]
        data: [alltypes, tpch, emptyalltypes]
        enable_verification: [true, false]
        randoms_config_filepath: [ "config.json" , "" ]
        exclude:
          - enable_verification: true
            fuzzer: sqlsmith
          - enable_verification: true
            fuzzer: duckfuzz_functions
          - randoms_config_filepath: "config.json"
            fuzzer: sqlsmith
          - randoms_config_filepath: ""
            fuzzer: duckfuzz_functions
          - randoms_config_filepath: "config.json"
            fuzzer: sqlsmith
          - randoms_config_filepath: ""
            fuzzer: duckfuzz_functions
    uses: ./.github/workflows/test_H_vals.yml
    with:
      fuzzer: ${{ matrix.fuzzer }}
      data: ${{ matrix.data }}
      timeout-minutes: 120
      max_queries: 10
      no-git-checks: true
      enable_verification: ${{ matrix.enable_verification }}
      randoms_config_filepath: ${{ matrix.randoms_config_filepath }}
  upterm:
    runs-on: ubuntu-latest
    needs:
    - build-duckdb
    - fuzzer
    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        limit-access-to-users: hmeriann
