name: This Workflow Reuses an external base_workflow
on:
  workflow_dispatch:
  pull_request:

jobs:
  build-duckdb:
    name: Build 
    uses: hmeriann/base_workflow/.github/workflows/base_workflow.yml@main
      with:
      git_url: duckdb/duckdb_sqlsmith
      git_tag: main
  fuzzer:
    name: Fuzzer
    needs:
    - build-duckdb
    uses: hmeriann/base_workflow/.github/workflows/fuzz.yml@main
    strategy:
      fail-fast: false
      matrix:
        fuzzer: [duckfuzz, sqlsmith, duckfuzz_functions]
        data: [emptyalltypes]
    with:
        fuzzer: ${{ matrix.fuzzer }}
        data: ${{ matrix.data }}
        timeout-minutes: 20
        dry: --dry
