name: Test - All Benchmark timings (RN) (incl. combinations of list_aggregates)
on:
  workflow_dispatch:
env:
  gh_issue_repo: hmeriann/test_
  GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: Build DuckDB versions and link the benchmarks
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_BENCHMARK: 1
      BUILD_HTTPFS: 1
      BUILD_JSON: 1

    steps:
      - uses: actions/checkout@v4
        with:
          repository: hmeriann/duckdb
          ref: 0e1492944c3496fb9f3944e192f0e411eb7f8db3
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests

      - name: Build
        shell: bash
        run: make 
      
      - run: |
          python scripts/regression_test_runner.py --old=build/release/benchmark/benchmark_runner --new=build/release/benchmark/benchmark_runner --benchmarks=.github/regression/realnest.csv  --verbose --threads=2
 
      # - name: Upload result
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: rnbm_all.txt
      #     name: rnbm_all.txt
