name: Test - All Benchmark timings (RN) (incl. combinations of list_aggregates)
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  BASE_BRANCH: ${{ github.base_ref || (endsWith(github.ref, '_feature') && 'feature' || 'main') }}
jobs:
  build:
    name: Build DuckDB versions and link the benchmarks
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_BENCHMARK: 1
      BUILD_HTTPFS: 1
      BUILD_JSON: 1
      # BUILD_TPCH: 1
      # BUILD_TPCDS: 1
      # BUILD_JEMALLOC: 1
      # CORE_EXTENSIONS: "inet"

    steps:
      - uses: actions/checkout@v4
        with:
          repository: hmeriann/duckdb
          ref: real-nest-benchmarks
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests

      # - name: Build
      #   shell: bash
      #   run: make 
      
      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}

      - name: Build
        shell: bash
        run: |
          make debug
          git clone --branch main https://github.com/duckdb/duckdb.git --depth=1
          cd duckdb
          make debug
          cd ..

      - run: cat .github/regression/realnest.csv
      - run: cat benchmark/realnest/load.sql
      - name: Regression Test CSV
        if: always()
        shell: bash
        run: |
          python scripts/regression_test_runner.py --old=duckdb/build/debug/benchmark/benchmark_runner --new=build/debug/benchmark/benchmark_runner --benchmarks=.github/regression/csv.csv --verbose --threads=2
      - run: |
          python scripts/regression_test_runner.py --old=build/debug/benchmark/benchmark_runner --new=build/debug/benchmark/benchmark_runner --benchmarks=.github/regression/realnest.csv  --verbose --threads=2
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      # - name: Upload result
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: rnbm_all.txt
      #     name: rnbm_all.txt
