name: Test Simple WR
on:
  workflow_dispatch:

jobs:
  define-matrix:
    name: Check if feature branch exists and define matrix
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.branches.outputs.branches }}
    steps:
      - id: branches
        run: | 
          echo 'branches=["main", "feature"]' >> "$GITHUB_OUTPUT"

  configure:
    name: Configure mount and download benchmark data
    needs: 
      - define-matrix
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  build:
    name: Build DuckDB versions and link the benchmarks
    needs: 
      - define-matrix
      - configure
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.define-matrix.outputs.branches) }}
    runs-on: ubuntu-latest
    outputs:
      builds: ${{ steps.successful-builds.outputs.builds }}
    steps:
      - name: Build old and current
        shell: bash
        run: |
          echo ${{ matrix.branch }} 🐣
          
      - id: successful-builds
        if: ${{ job.status == 'success' }}
        run: |
          echo "builds=${{ matrix.branch }}" >> "$GITHUB_OUTPUT"

  debug:
    name: Debug
    if: always()
    needs: 
      - define-matrix
      - configure
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mtr: ${{ needs.build.outputs.builds }
    steps:
      - name: Debug Outputs
        run: echo ${{ matrix.mtr }}

  run-tests:
    name: Run Regression Tests
    if: always()
    needs: 
      - define-matrix
      - configure
      - build
      - debug
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ needs.build.outputs.builds }}
        test: ['one', 'two', 'three', 'four']
        
    steps:
      - name: Run Regression Test
        continue-on-error: true
        shell: bash
        run: |
          echo ${{ matrix.branch }} ⏩️ ${{ matrix.test }} ⏹️
          
  collect-issues:
    name: Collect failures
    needs: 
      - define-matrix
      - configure
      - build
      - run-tests
    if: always()
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        branch: ${{ fromJSON(needs.define-matrix.outputs.branches) }}
    steps:
      - name: Collect issues on Benchmarks
        if: contains(github.ref_name, 'main')
        run: |
          echo "touch ~/previous_failed_${{ matrix.branch }}.txt"
      
  file-issue:
    name: File Issue
    needs: 
      - define-matrix
      - configure
      - build
      - run-tests
      - collect-issues
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: File issue on preparation steps
        if: |
            contains(github.ref_name, 'main') && 
            (needs.configure.result != 'success' || 
            needs.build.result != 'success')
        run: |
          echo "Failed to run Weekly Regression Benchmarks"
      - name: Send issue to gh
        run: |
          echo "REGRESSIONS DETECTED"
