name: Test FEATURE Exists
on: workflow_dispatch
jobs:
  check-feature:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: actions/checkout@v4
        with:
          repository: duckdb/duckdb
          ref: blabla
          fetch-depth: 0
      
      - name: define-matrix
        if: always()
        run: |
          count=$(git log origin/feature --since="7 days ago" | wc -l)
          if [steps.check.outcome == 'failure' && $count == 0 ]; then
            echo 'branches=["main"]' >> $GITHUB_OUTPUT
          else
            echo 'branches=["main", "feature"]' >> $GITHUB_OUTPUT
          fi
        
