name: Test - file issue when no regressions detected
# https://github.com/duckdblabs/duckdb-internal/issues/2931
on:
  workflow_dispatch:
env:
  gh_issue_repo: hmeriann/test_
  GH_TOKEN: ${{ github.token }}
jobs:
  run-tests:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      file_name: ${{ steps.create.outputs.file_name }}
    steps:    
      - run: |
          wget https://drive.google.com/file/d/1T1o7e_3qfYCcXq6eFhBLw6o9KvttS-4m/view?usp=share_link --output-document regression_output_tpcds_main.txt
          wget https://drive.google.com/file/d/1hkjahg7G1ErJh6DJ4WqZvAKDQr412Y_P/view?usp=share_link --output-document regression_output_micro_extended_main.txt
          wget https://drive.google.com/file/d/1MmljcZBnO5MdCBkOb6RLgUEB7wP-1sBo/view?usp=share_link --output-document regression_output_large_tpch_main.txt
          wget https://drive.google.com/file/d/1SiV2GksVENu7Xo9Xj6Gtq0pljH0x_1Vw/view?usp=share_link --output-document regression_output_large_ingestion_main.txt
          wget https://drive.google.com/file/d/1GnE9rDb1HEILK7H02ZuA-ki46mpWRX2M/view?usp=share_link --output-document regression_output_large_tpcds_main.txt
      - run: ls -lah
      - name: Collect issues
        run: |
          # collect issues on benchmarks runs
          for output in regression*.txt; do
            echo ❇️ $(cat $output)
            printf " *️⃣ [ Regression Test $output ]\n" >> issue_body.txt
            printf "Regression Output \n \`\`\` \n $(awk '/REGRESSIONS DETECTED/,/OTHER TIMINGS/' $output) \n \`\`\` \n"  >> issue_body.txt
          done
      - name: Upload issue_body
        uses: actions/upload-artifact@v4
        if: success()
        with:
          path: ./issue_*.txt
          name: issue_body

  file-issue:
    name: File Issue
    needs: 
      - run-tests
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        if: always()
        uses: actions/download-artifact@v4
        with:
          pattern: issue_body*
          merge-multiple: true
      - run: ls -R issue_body
          
      - name: File issue on Benchmarks
        if: contains(github.ref_name, 'main') && needs.build.result != 'success'
        run: |
          if grep -q "REGRESSIONS DETECTED" issue_body*; then
            cat issue_body* >> report.txt
            gh issue create --repo ${{ env.gh_issue_repo }} --title "TEST: Weekly Regression Test Failure" --body-file report.txt
          fi
