# Here I test that the workflow creates a valid matrix with the branch names.
# It should be only "main" if the "feature" doesn't exist or exists but doesn't have recent commits to it.

name: Test FEATURE Exists
on: workflow_dispatch
jobs:
  check-feature:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.branches.outputs.branches }}
    steps:
      - id: check
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: duckdb/duckdb
          ref: blahblah
          fetch-depth: 0
      
      - name: define-matrix
        id: check_branches
        if: always()
        run: |
          count=$(git log origin/feature --since="7 days ago" | wc -l)
          if [[ "${{ steps.check.outcome }}" == "failure" ]] || [[ $count -eq 0 ]]; then
            echo 'branches=[ "main" ]' >> $GITHUB_OUTPUT
          else
            echo 'branches=[ "main", "feature" ]' >> $GITHUB_OUTPUT
          fi
          
      - name: View output from previous step
        run: |
          echo "Branches output: ${{ steps.check_branches.outputs.branches }}"
